name: CoordinatesBook
version: 2
main: net.axiiom.CoordinatesBook.Main.CoordinatesBookPlugin
api-version: 1.21

commands:
  coords:
    description: open coordinates book
  fasttravel:
    description: managed by coord book
  savecoordinate:
    description: managed by coord book
    aliases: [savecoord, sc]
  removecoordinate:
    description: managed by coord book
  renamecoordinate:
    description: managed by coord book
  compasstarget:
    description: managed by coord book
  sharecoordinate:
    description: managed by coord book
  receivecoordinate:
    description: managed by coord book
  denycoordinate:
    description: managed by coord book